import {translate} from '@docusaurus/Translate';
import React from 'react';
import Layout from '@theme/Layout';
import Link from '@docusaurus/Link';
import useDocusaurusContext from '@docusaurus/useDocusaurusContext';

export default function Community() {
  const {siteConfig} = useDocusaurusContext();
  const url = siteConfig.customFields.discussionUrl;
  return <Layout title={translate({id: "site.get.involved", message: "Get involved"})} description={translate({id: "site.find.your.way.to.take.part.in.the.children.s.international", message: "Find your way to take part in The Children’s International."})}><main className="community-page page-width"><span className="eyebrow">{translate({id: "site.let.s.start.with.listening", message: "LET’S START WITH LISTENING"})}</span><h1>{translate({id: "site.every.voice.has.a.place", message: "Every voice has a place."})}</h1><p className="intro">{translate({id: "site.a.world.that.respects.children.starts.with.people.who.listen.get.to.know.our.purpose.and.think.about.what.you.would.change.in.your.community", message: "A world that respects children starts with people who listen. Get to know our purpose and think about what you would change in your community."})}</p><div className="community-panel"><h2>{translate({id: "site.join.the.conversation", message: "Join the conversation"})}</h2>{url ? <><p>{translate({id: "site.read.our.community.principles.before.taking.part.in.our.discussion.space", message: "Read our community principles before taking part in our discussion space."})}</p><a className="pill primary" href={url} target="_blank" rel="noopener noreferrer">{translate({id: "site.open.discussions", message: "Open discussions ↗"})}</a></> : <p>{translate({id: "site.our.public.discussion.space.is.being.prepared.in.the.meantime.explore.our.priorities.and.community.principles", message: "Our public discussion space is being prepared. In the meantime, explore our priorities and community principles."})}</p>}<Link className="principles-link" to="/about/community-principles">{translate({id: "site.read.the.community.principles", message: "Read the community principles →"})}</Link></div><h2>{translate({id: "site.start.where.you.are", message: "Start where you are."})}</h2><ul><li>{translate({id: "site.read", message: "Read"})} <Link to="/about/our-purpose">{translate({id: "site.our.purpose", message: "our purpose"})}</Link> {translate({id: "site.and.talk.about.it.with.someone.you.trust", message: "and talk about it with someone you trust."})}</li><li>{translate({id: "site.consider.which", message: "Consider which"})} <Link to="/about/our-priorities">{translate({id: "site.priorities", message: "priorities"})}</Link> {translate({id: "site.matter.most.in.your.community", message: "matter most in your community."})}</li><li>{translate({id: "site.make.room.for.children.s.ideas.in.everyday.conversations", message: "Make room for children’s ideas in everyday conversations."})}</li></ul></main></Layout>;
}
