import {translate} from '@docusaurus/Translate';
import React from 'react';
import Layout from '@theme/Layout';
import Link from '@docusaurus/Link';
import useDocusaurusContext from '@docusaurus/useDocusaurusContext';

export default function Community() {
  const {siteConfig} = useDocusaurusContext();
  const url = siteConfig.customFields.discussionUrl;
  return <Layout title={translate({id: "site.get.involved", message: "Get involved"})} description={translate({id: "site.find.your.way.to.take.part.in.the.children.s.international", message: "Find your way to take part in The Children’s International."})}><main className="community-page page-width"><span className="eyebrow">{translate({id: "site.let.s.start.with.listening", message: "LET’S START WITH LISTENING"})}</span><h1>{translate({id: "site.every.voice.has.a.place", message: "Every voice has a place."})}</h1><p className="intro">{translate({id: "site.a.world.that.respects.children.starts.with.people.who.listen.get.to.know.our.purpose.and.think.about.what.you.would.change.in.your.community", message: "A world that respects children starts with people who listen. Get to know our purpose and think about what you would change in your community."})}</p><div className="community-panel"><h2>{translate({id: "site.join.the.conversation", message: "Join the conversation"})}</h2>{url ? <><p>{translate({id: "site.share.your.ideas.in.our.discussion.space", message: "Share your ideas in our discussion space."})}</p><a className="pill primary" href={url} target="_blank" rel="noopener noreferrer">{translate({id: "site.open.discussions", message: "Open discussions ↗"})}</a></> : <p>{translate({id: "site.discussions.pending.explore.ideas", message: "Our public discussion space is being prepared. In the meantime, explore our ideas for children’s rights."})}</p>}<Link className="principles-link" to="/about/">{translate({id: "site.browse.all.ideas", message: "Browse all ideas →"})}</Link></div><h2>{translate({id: "site.start.where.you.are", message: "Start where you are."})}</h2><ul><li>{translate({id: "site.read", message: "Read"})} <Link to="/about/">{translate({id: "site.our.ideas", message: "our ideas"})}</Link> {translate({id: "site.and.talk.about.it.with.someone.you.trust", message: "and talk about it with someone you trust."})}</li><li>{translate({id: "site.consider.which", message: "Consider which"})} <Link to="/about/">{translate({id: "site.ideas", message: "ideas"})}</Link> {translate({id: "site.matter.most.in.your.community", message: "matter most in your community."})}</li><li>{translate({id: "site.make.room.for.children.s.ideas.in.everyday.conversations", message: "Make room for children’s ideas in everyday conversations."})}</li></ul></main></Layout>;
}
